### ISSUE TITLE
Shell's log density for cr shells incorrect

### ISSUE THREAD

**Issue by gerrygralton** [kateharborne/SimSpin#3]
Shell density should be log(1/2) lower than calculated on line 239 of sim_analysis.R.

`      profile$logp[j] =
        log10(grp_mass / (pi * rmax * ((profile$cr[j] * profile$cr[j]) - (rbin_labels[j] * rbin_labels[j]))))`
should be 
`      profile$logp[j] =
        log10(grp_mass / (pi * (rmax * 2) * ((profile$cr[j] * profile$cr[j]) - (rbin_labels[j] * rbin_labels[j]))))`

**Comment by kateharborne** [comment]
Fixed with commit 66baa1928c95ffe5818d738e110d5afc0c058b9e - thanks @gerrygralton!
