### ISSUE TITLE
Ingesting Horizon-AGN inputs

### ISSUE THREAD

**Issue by kateharborne** [kateharborne/SimSpin#42]
Tasks required to make SimSpin compatible with HorizonAGN cut-out galaxies:

Updates to `make_simspin_file` and `utilities` functions
- [ ] Compute SFR for gas cells? (If not present in Fortran outputs)
- [ ] Compute cell sizes for proper gas field sampling (how cells work with n_gas_spawn)
- [ ] Incorporate read script for HorizonAGN files

**Comment by syj3514** [comment]
Initial mass of stars
SFR of cells --> saved in raw output? if not, calculate it
Metallicity unit
Find heavy elements data

**Comment by kateharborne** [comment]
- [ ] Update gh-pages to include the groups necessary for each particle type.

**Comment by kateharborne** [comment]
Updated documentation for writing SimSpin compatible HDF5 files can be found here: https://kateharborne.github.io/SimSpin/examples/generating_hdf5.html
