### ISSUE TITLE
Error when building datacube with pixel resolution below 0.5 arcseconds

### ISSUE THREAD

**Issue by Andrei-Ristea** [kateharborne/SimSpin#69]
When running the **build_datacube** function (method = 'velocity'), with a spatial_res < 0.5 arcsec (**telescope** function), the execution fails with the following error message: 

**Error in Cfits_write_col(filename = filename, data = table[[i]], nrow = nrow, : 
Error when invoking fits_write_col: column exceeds width of table**

The telescope & observing strategy functions are set up as follows:

 **ifu = telescope(type = "IFU", 
                fov = 50, # field-of-view in arcsec
                aperture_shape = "circular", # shape of fov
                wave_range = c(3700,5700), # given in angstroms
                wave_centre = 4700, # central wavelength given in angstroms
                wave_res = 1.04, # wavelength resolution in angstroms
                _spatial_res = 0.25_, # size of spatial pixels in arcsec
                filter = "r", # filter for calc of particle luminosity
                lsf_fwhm = 2.0, # full-width half-max of line-spread-function
                signal_to_noise = 10) # s/n ratio per angstrom**

 **strategy = observing_strategy(dist_z = 0.09, # redshift distance the galaxy is placed
                              inc_deg = 90, # projection (0 - face-on, 90 - edge-on)
                              twist_deg = 0, # angle of observation (longitude)
                              pointing_kpc = c(0,0), # pointing of the centre of the telescope
                              blur = T, # whether seeing conditions are included
                              fwhm = fwhm_i, # the fwhm of the blurring kernel in arcsec
                              psf = "Moffat") # the shape of the blurring kernel**

**Comment by kateharborne** [comment]
Thanks @Andrei-Ristea 

I think this is due to a large array being collapsed and written to a single table element within the FITS file writing process. Similar to the old Issue #59. I will remove all collapsed arrays and see if this sorts the issue...
