### ISSUE TITLE
hdf5 file extracted from Illustris not compatible with Make SimSpin

### ISSUE THREAD

**Issue by amandaeac** [kateharborne/SimSpin#95]
Error raised: should match format "data-url"
But the file is in the right format (hdf5) and have both Header and PartType4. I tested using different objects and the same error persists.

**Comment by kateharborne** [comment]
Hi @amandaeac - I think this report relates to the web application, and I believe had to do with the version mismatch between the application and the GitHub latest release, though I'm concerned that other objects (non-IllustrisTNG galaxies) are also causing the same error. 

The web application is being updated to v2.6.0, which will have support for building IllustrisTNG files. Currently we are experiencing some odd errors that the `hdf5r` package is no longer accessible to SimSpin when attempting installation. We're investigating these issues and hopefully will have a solution soon!

**Comment by kateharborne** [comment]
This is actually a problem in the implementation followed by SimSpin - when using TNG files from the database, there are a number of Datasets included in each HDF5 file that do not have attributes stored against them. In reality, this shouldn't interrupt SimSpin's functionality, becasue we don't use these for the build_datacube process, but the code does a check at file read in that all HDF5 Datasets have the required attributes and fails if not. 

Branch opened to support a fix for this. 

- [ ] Make it possible to use an HDF5 file cutout from the TNG database directly, without any user modifcations.
